name: package_assets_generator
description: Package assets generator.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  very_good_analysis: ^7.0.0
dependencies:
  build: ^2.4.1
  path: ^1.9.0
